### ISSUE TITLE
Plotting multiple time series's

### ISSUE THREAD

**Issue by m0nhawk** [NatelEnergy/grafana-plotly-panel#9]
Is it possible to plot several time series's on one plot?

I'm working with daily stocks data and there are multiple values for each timestamp: Open, Close and Avg of the same magnitude (so, I don't need an additional Y axis).

For now I can only plot one of it, but I'd like to plot all at once.

It would be nice to have such feature.

**Comment by ryantxu** [comment]
yes, i would love to figure out the best way to have multiple traces.  Just like in:

https://plot.ly/create/

**Comment by rtmaster** [comment]
are you talking about something like this?

https://plot.ly/create/?fid=chelsea_lyn:14921

My proposal for managing this in the plugin modifying the "Display Tab":
- Keep in the "Plot" section only the "Options" items
- Collapse "X Axis" and "Y Axis" sections into a section called "Series 1" along with "Markers" and "Lines" from "Plot"
-Introduce two new sections "Series 2" and "Series 3" containing same as above

I guess the backend would have to be modified to save this additional configuration data in the database and use the plotly JS to render up to 3 series instead of 1

That would be awesome!

**Comment by rtmaster** [comment]
Hi @ryantxu do you have any feedback on my proposal?

**Comment by ryantxu** [comment]
yes, proposal sounds great.  I don't have time to work on it soon.  but pull requests are always welcome!

**Comment by rtmaster** [comment]
hey @ryantxu do you think you will add this feature?

**Comment by ryantxu** [comment]
It would be great.  It is not on my immediate need/TODO list, but patches are always welcome

**Comment by Anna-Fedorova** [comment]
Yeah, I also faced with the problem to have x-y chart with multiple plots
It would be nice to have such opportunity

**Comment by hami0314** [comment]
+1

**Comment by ryantxu** [comment]
supported in 0.0.5... will try to release soon, but test off master if you have a chance 😃
